## server config
server:
  port: 8080
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
      repository-type: indexed
  data:
    redis:
      host: 172.30.10.25
      port: 6379
      password: insoft!23